version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show Current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - app-{{ checksum "package.json" }}
            - app-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.json" }}

  deploy-to-aws-s3:
    docker:
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      -checkout
      -run:
          name: Show Current branch
          command: echo ${CIRCLE_BRANCH}
      -run:
          name: Installing AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y awscli
            sudo apt-get install -y python-pip python-dev build-essential
      -run: Build Project
          name: Build Project
          command: |
            npm install
            npm run build
            cd build
            zip ../build.zip -r *.[^.]*
            echo "Build Completed"
      -run:
          name: Deploy to S3
          command: |
            aws s3 cp build.zip s3://react-cinema-devvvv/build.zip
            echo "Deployed to S3"